### ISSUE TITLE
Cutting down yum requirements

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qt-feedstock#56]
It appears some of things listed in [`yum_requirements.txt`]( https://github.com/conda-forge/qt-feedstock/blob/dba633d8b90848b962754e7db53791196a7760aa/recipe/yum_requirements.txt ) have since become packages in `conda-forge`. Perhaps it is time to switch to the `conda-forge` packages and drop these from `yum_requirements.txt`. In particular would note [`chrpath`]( https://github.com/conda-forge/qt-feedstock/blob/dba633d8b90848b962754e7db53791196a7760aa/recipe/yum_requirements.txt#L4 ), [`dbus`]( https://github.com/conda-forge/qt-feedstock/blob/dba633d8b90848b962754e7db53791196a7760aa/recipe/yum_requirements.txt#L7 ), and [`ruby`]( https://github.com/conda-forge/qt-feedstock/blob/dba633d8b90848b962754e7db53791196a7760aa/recipe/yum_requirements.txt#L11 ). Though the X11 packages also fit into this category as well. Just the latter may need some more [buy-in]( https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/7 ) before we can use them here. This should also hopefully resolve some of the issues encountered by users trying to install this package both in terms of missing these requirements and having versions that are incompatible with the ones we used to build the package.

**Comment by jakirkham** [comment]
Seems we are now down to `chrpath` and `ruby`. Should be easy to switch these over to `conda-forge` packages.

**Comment by ocefpaf** [comment]
Done in #102

**Comment by jakirkham** [comment]
Thanks @ocefpaf. I'm still seeing the [`yum_requirements.txt`]( https://github.com/conda-forge/qt-feedstock/blob/master/recipe/yum_requirements.txt ). Was that meant to be removed?
